import React, { useState } from 'react';
import './styles.scss';
type Variant = 'market_analysis' | 'manual_trader' | 'ai_trader' | 'free_bots' | 'copy_trading' | 'accumulators' | 'competition';
const content: Record<Variant, { eyebrow: string; title: string; intro: string; action: string }> = {
 market_analysis:{eyebrow:'Signal desk',title:'See the market before you trade it.',intro:'Build a focused view of synthetic indices with price context, momentum and volatility in one workspace.',action:'Open analysis workspace'},
 manual_trader:{eyebrow:'Execution desk',title:'Trade with a plan, not a hunch.',intro:'Prepare your contract, risk limits and exit rules before sending an order to Deriv.',action:'Prepare a trade'},
 ai_trader:{eyebrow:'AI strategy lab',title:'Turn an idea into testable rules.',intro:'Describe your setup and let D-Zenith help structure it. You stay in control of every signal and execution.',action:'Generate a ruleset'},
 free_bots:{eyebrow:'Strategy library',title:'Start with a strategy you can understand.',intro:'Explore reusable bot ideas for synthetic indices and make them your own before running them.',action:'Browse strategies'},
 copy_trading:{eyebrow:'Playbooks',title:'Follow process, not promises.',intro:'Compare transparent strategy playbooks and review their logic before you decide what belongs in your account.',action:'Explore playbooks'},
 accumulators:{eyebrow:'Accumulators',title:'Shape exposure with discipline.',intro:'A dedicated space for accumulator ideas, contract settings and controlled experimentation.',action:'Configure an accumulator'},
 competition:{eyebrow:'Challenges',title:'Make consistency the competition.',intro:'Track practice performance and compete on process, risk control and repeatable execution.',action:'View challenges'}
};
export default function DZenithTools({variant}:{variant:Variant}){
 const data=content[variant]; const [notes,setNotes]=useState(''); const [generated,setGenerated]=useState(false); const isAi=variant==='ai_trader';
 return <main className='dz-tool-page'><section className='dz-tool-hero'><div className='dz-tool-copy'><span className='dz-eyebrow'>{data.eyebrow}</span><h1>{data.title}</h1><p>{data.intro}</p><div className='dz-action-row'><button className='dz-primary' onClick={()=>setGenerated(true)}>{data.action} <span>→</span></button><span className='dz-demo-note'>Demo-first · You approve execution</span></div></div><div className='dz-signal-card'><div className='dz-card-top'><span>Market pulse</span><span className='dz-live-dot'>● Live</span></div>{['Volatility 75','Boom 500','Crash 1000'].map((name,index)=><div className='dz-pulse-row' key={name}><span>{name}</span><strong>{index===1?'+0.84%':index===2?'-0.31%':'+0.42%'}</strong><div className='dz-meter'><i style={{width:String(54+index*13)+'%'}} /></div></div>)}<small>Public market data · Deriv synthetic indices</small></div></section><section className='dz-tool-grid'><div className='dz-panel dz-form-panel'><div className='dz-panel-heading'><span>Workspace</span><span className='dz-chip'>Risk-aware</span></div>{isAi?<><label>Describe your setup<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder='Example: look for a volatility expansion after a quiet range...' /></label><div className='dz-form-row'><label>Market<select><option>Volatility 75</option><option>Boom 500</option><option>Crash 1000</option></select></label><label>Time horizon<select><option>5 minutes</option><option>15 minutes</option><option>1 hour</option></select></label></div><div className='dz-form-row'><label>Risk mode<select><option>Conservative</option><option>Balanced</option><option>Experimental</option></select></label><label>Stake limit<input placeholder='Demo account only' /></label></div><p className='dz-safety'>AI should explain the trade, not hide it. D-Zenith shows assumptions and rules before anything can be executed.</p></>:<><div className='dz-stat-grid'><div><small>Primary market</small><b>Volatility 75</b></div><div><small>Session bias</small><b className='positive'>Momentum ↑</b></div><div><small>Risk budget</small><b>1.0% max</b></div></div><div className='dz-chart-placeholder'><span>Strategy context</span><div className='dz-chart-line' /></div><p className='dz-safety'>Connect a Deriv account to load your personal balance, contracts and execution history.</p></>}{generated&&<div className='dz-result'><b>{isAi?'Ruleset drafted':'Workspace ready'}</b><span>Review the details before connecting or trading.</span></div>}</div><aside className='dz-panel dz-side-panel'><span className='dz-eyebrow'>D-Zenith principles</span><h2>Clarity compounds.</h2><ul><li>Explain every signal</li><li>Practice with demo funds</li><li>Set a loss limit first</li><li>Keep API tokens private</li></ul><button className='dz-secondary' onClick={()=>window.location.hash='dashboard'}>Back to desk</button></aside></section></main>;
}