const topics = [
    ['1 · Set up safely', 'Log in through Deriv and select a demo account. Account currency and demo/real status are verified before a trading ticket can be used. Nothing trades merely because you open a page.'],
    ['2 · Dashboard & Bot Builder', 'Use the restored Dashboard to import an XML file, open a saved bot or start a quick strategy. Free Bots imports compatible library strategies into Bot Builder. Save your existing work first. Review stake, contract and restart conditions; Run is a separate action.'],
    ['3 · Observe or investigate', 'Market Analysis is a live overview: price trace, high/low, tick-change variation and digit frequencies. Analysis Tool captures a fixed sample and measures historical next-tick parity matches and digit transitions. Historical percentages are not next-tick probabilities, profit forecasts or investment advice.'],
    ['4 · Manual Trader', 'Choose the market and contract, verify your selected account and request a quote. Review cost and terms, then confirm one purchase. Quotes expire after 10 seconds. Real accounts require BUY REAL. Refresh the contract to check settlement; use Sell only when Deriv permits early sale.'],
    ['5 · Accumulators', 'Choose an eligible market, stake, growth percentage and take-profit amount. The contract grows while ticks stay in the permitted range; a breach can lose the stake. Read the quoted terms before buying. You can request an early sale when available. A selected growth rate is not a guaranteed return.'],
    ['6 · Copy Trading', 'This uses Deriv’s legacy copy-trading facility where available. A lead trader must enable allow_copiers and provide their read-only copy token. Their account number alone is insufficient. Your own trading token authorizes your follower account; the app also requires a registered numeric legacy App ID. Review stake filters and confirm Start. Server-side copying may continue after closing the site: refresh the list and use Stop to end it. Never share passwords or withdrawal tokens.'],
    ['7 · Floating Auto Trader', 'The console continuously observes the shared selected market while the site is open. Choose parity frequency or direction rules, set limits and verify an account, then explicitly Start. It waits for a qualifying rule, quotes, buys one contract and waits for settlement before considering another. Minimizing the console or switching site tabs does not stop it. Hiding or closing the browser, stale data, changed market/account, or a reached limit stops new entries. Stop does not cancel an open contract.'],
    ['8 · When something goes wrong', 'An unconfirmed purchase is never automatically retried. Check the Deriv statement and use the contract-status controls to reconcile known IDs. If no ID returned, seek support before another purchase. Do not clear browser storage to bypass the pending-purchase lock. Manual tickets and Auto Trader share a browser-account lock; stop/disconnect one before using the other. Other browsers or devices are not covered by that lock.'],
    ['9 · Hosting & advanced tools', 'The current Auto Trader runs in this visible browser, not on an always-on server. Unattended hosting needs a separate secure execution service and explicit account authorization; deploying this frontend to Vercel alone does not provide that. EA Bots concerns MT5 expert advisors, not browser XML. Competition is a preview until an actual organiser, rules and backend are configured.'],
];
export default function PlatformGuide(){return <section className='dz-platform-guide'><span className='dz-eyebrow'>D-ZENITH FIELD GUIDE</span><h1>Know the tool. Control the trade.</h1><p>Begin with demo funds. There is no guaranteed winning strategy, and automated trading can lose money quickly.</p>{topics.map(([title,body])=><details key={title}><summary>{title}</summary><p>{body}</p></details>)}<p>Official reference: <a href='https://api.deriv.com/docs/core-concepts/copytrading/' target='_blank' rel='noreferrer'>Deriv copy trading</a> · <a href='https://developers.deriv.com/docs/trading/' target='_blank' rel='noreferrer'>Trading APIs</a></p></section>;}
